config/routes.rb
Rails.application.routes.draw do
  resources :stockists
  post 'emaillist/subscribe' => 'emaillist#subscribe'

  get 'products/search' => 'products#search', as: 'search_products'

  get 'pages/index'

  get 'pages/about'

  get 'pages/location'

  get 'pages/help'

  devise_for :users
  resources :categories
  resources :categories
  resources :designers
  resources :category_names

  resources :products

  resource :cart, only: [:show] do
    post "add", path: "add/:id", on: :member
    delete 'remove', path: 'destroy/:id'
    get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update ] do
    member do
      get :new_payment
      post :pay
    end
  end
  

  

  root 'pages#index'

end

app/models/designer.rb
class Designer < ActiveRecord::Base
	has_many :products
	has_many :pages
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  before_action :set_designer, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @designers = Designer.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
     @products = @designer.products
  end

  # GET /categories/new
  def new
    @designer = Designer.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @designer = Designer.new(designer_params)

    respond_to do |format|
      if @designer.save
        format.html { redirect_to @designer, notice: 'Designer was successfully created.' }
        format.json { render :show, status: :created, location: @designer }
      else
        format.html { render :new }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @designer.update(designer_params)
        format.html { redirect_to @designer, notice: 'Designer was successfully updated.' }
        format.json { render :show, status: :ok, location: @designer }
      else
        format.html { render :edit }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @designer.destroy
    respond_to do |format|
      format.html { redirect_to designers_url, notice: 'Designer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_designer
      @designer = Designer.includes(:products).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def designer_params
      params.require(:designer).permit(:designer_name)
    end
end

app/views/designers/_form.html.erb
<%= form_for(@designer) do |f| %>
  <% if @designer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@designer.errors.count, "error") %> prohibited this designer from being saved:</h2>

      <ul>
      <% @designer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="form-group">
    <%= f.label :designer_name %><br>
    <%= f.text_field :designer_name, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>  
<% end %>

app/views/designers/_table.html.erb
<div class="container-fluid">
<div class="row product_top">
 
<% products.each do |product| %>
<div class="col-lg-3 col-sm-6 col-xs-12 center-block " >
  
   <%= image_tag product.image, height: "300", class: "img-responsive" %>
 

  <div class="product_description">

    <h5><%= link_to product.name, product %></h5>

    <p><%= product.description %></p>
    <p>In stock: <%= product.stock_quantity %> items.</p>
    <p class="price"> <%= number_to_currency product.price %></p>
    <p><%= social_share_button_tag(products.name) %></p>

  </div>
      

  </div>
 <% end %>
 
  </div>
  </div>
 

app/views/designers/edit.html.erb
<div class="container">

	<div class="admin-wrapper">

		<h3>Editing Category</h3>

			<%= render 'form' %>

				<%= link_to 'Show', @designer %> |
				<%= link_to 'Back', designers_path %>
	</div>
</div>	
				

app/views/designers/index.html.erb
<div class="container">
<div class="admin-wrapper">
<p id="notice"><%= notice %></p>


<h3>Listing Designers</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Designer Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designers.each do |designer| %>
      <tr>
        <td><%= designer.designer_name %></td>
        <td><%= link_to 'Show', designer %></td>
        <td><%= link_to 'Edit', edit_designer_path(designer) %></td>
        <td><%= link_to 'Destroy', designer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<% if current_user && current_user.admin? %>
  <%= link_to 'New Designer', new_designer_path, class: 'admin-buttons' %>
<% end %>
  
</div>
</div>

app/views/designers/new.html.erb
<div class="container">

	<div class="admin-wrapper">
			<h3>New Designer</h3>

			<%= render 'form' %>

			<%= link_to 'Back', designers_path, class: 'admin-buttons' %>
	</div>
</div>

app/views/designers/show.html.erb
<header id="necklace_header">
<h1>
  <%= @designer.designer_name %>
</h1>
</header>



<%= render "designers/table", products: @products %>



<% if current_user && current_user.admin? %>
	<%= link_to 'Edit', edit_designer_path(@designer) %> |
<% end %>

<%= link_to 'Back', root_path %>