config/routes.rb
Rails.application.routes.draw do
  resources :stockists
  post 'emaillist/subscribe' => 'emaillist#subscribe'

  get 'products/search' => 'products#search', as: 'search_products'

  get 'pages/index'

  get 'pages/about'

  get 'pages/location'

  get 'pages/help'

  devise_for :users
  resources :categories
  resources :categories
  resources :designers
  resources :category_names

  resources :products

  resource :cart, only: [:show] do
    post "add", path: "add/:id", on: :member
    delete 'remove', path: 'destroy/:id'
    get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update ] do
    member do
      get :new_payment
      post :pay
    end
  end
  

  

  root 'pages#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	has_many :pages
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
     @products = @category.products
     @images  = ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg"]
     @random_no = rand(5)
     @random_image = @images[@random_no]
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.includes(:products).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper


end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control'%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>  
<% end %>

app/views/categories/_table.html.erb
<div class="container-fluid">
  <div class="row product_top">
 
    <% products.each do |product| %>
      <div class="col-lg-3 col-sm-6 col-xs-12 center-block " >

  <%= link_to product_path (product) do %>
                <%= image_tag product.image.url(:medium), class: "img-responsive" %>
            <% end %>

        <div class="product_description">

          <h5><%= link_to product.name, product %></h5>
          <p><%= product.description %></p>
          <p class="price"> <%= number_to_currency product.price %></p>
          <p><%= social_share_button_tag(products.name) %></p>

        </div>
      

      </div>
    <% end %>
 
  </div>
</div>
 

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container">
<div class="admin-wrapper">

<p id="notice"><%= notice %></p>

<h3>Listing Categories</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user && current_user.admin? %>
  <%= link_to 'New Category', new_category_path, class: 'admin-buttons'%>
<% end %>

</div>
</div>

app/views/categories/new.html.erb
<div class="container">

	<div class="admin-wrapper">
		<h3>New Category</h3>

			<%= render 'form' %>

		<%= link_to 'Back', categories_path, class: 'admin-buttons'%>
	</div>
</div>

app/views/categories/show.html.erb
<header id="necklace_header" class="img-responsive">


  <img src="/assets/rand_headers/<%= @random_image%>", style='height:auto;width:100%;' >
	
	<h1 ><%= @category.name %></h1>
</header>

	



<%= render "categories/table", products: @products %>



<% if current_user && current_user.admin? %>
	<%= link_to 'Edit', edit_category_path(@category) %> |
<% end %>
	
<%= link_to 'Back', root_path %>