config/routes.rb
Rails.application.routes.draw do
  resources :stockists
  post 'emaillist/subscribe' => 'emaillist#subscribe'

  get 'products/search' => 'products#search', as: 'search_products'

  get 'pages/index'

  get 'pages/about'

  get 'pages/location'

  get 'pages/help'

  devise_for :users
  resources :categories
  resources :categories
  resources :designers
  resources :category_names

  resources :products

  resource :cart, only: [:show] do
    post "add", path: "add/:id", on: :member
    delete 'remove', path: 'destroy/:id'
    get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update ] do
    member do
      get :new_payment
      post :pay
    end
  end
  

  

  root 'pages#index'

end

app/models/cart.rb
class Cart
	attr_reader :items

	def self.build_from_hash hash
		items = if hash ["cart"] then 
			hash["cart"] ["items"].map do |item_data|
		CartItem.new item_data["product_id"], item_data["quantity"]
		end

	else
		[]
	end

		new items
	end


  def initialize items = []
    @items = items
  end

  def add_item product_id
    item = @items.find { |item| item.product_id == product_id }
    if item
      item.increment
    else
      @items << CartItem.new(product_id)
    end
  end

  def empty?
    @items.empty?
  end

  def count
    @items.length
  end

  def serialize 
  	items = @items.map do |item| 
  		{
  			"product_id" => item.product_id, 
  			"quantity" => item.quantity
  		}
  	end

  	{
  		
  			"items" => items
  	}


  end

  def total_price
    @items.inject(0) { |sum, item| sum + item.total_price }
  end


  	

end

app/models/cart_item.rb
class CartItem
attr_reader :product_id, :quantity

  def initialize product_id, quantity = 1
    @product_id = product_id
    @quantity = quantity
  end

  def increment
    @quantity = @quantity + 1
  end

  def product
    Product.find product_id
  end

  def total_price
    product.price * quantity
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	has_many :pages
end

app/models/designer.rb
class Designer < ActiveRecord::Base
	has_many :products
	has_many :pages
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user, dependent: :destroy 
  has_many :order_items, dependent: :destroy 

  def total_price
  	order_items.inject(0) { |sum, item| sum + item.total_price }
  end

  STATES = [
  	[ "New", :new ], 
  	[ "Dispatched", :dispatched ]

  ]
end

app/models/order_form.rb
class OrderForm
	include ActiveModel::Model

	attr_accessor :user, :order #credit_card
	attr_writer :cart

	def save

		set_password_for_user

		if valid?
			persist
			true
		else
			false
		end
	end

	def has_errors?
		user.errors.any?
	end

	private

	def valid?
		user.valid?
	end

	def persist
		user.save
		@order = Order.create! user: user

		build_order_items
	end

	def set_password_for_user
		user.password = Digest::SHA1.hexdigest(user.email + Time.now.to_s)[0..8]
	end

	def build_order_items
		@cart.items.each do |item|
			@order.order_items.create! product_id: item.product_id, quantity: item.quantity
		end
	end


end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order, dependent: :destroy 
  belongs_to :product, dependent: :destroy 

  def total_price
  	self.quantity * self.product.price
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
	mount_uploader :image, ImageUploader

	has_many :products
	belongs_to :category
	belongs_to :designer
end

app/models/product.rb
class Product < ActiveRecord::Base
	

	mount_uploader :image, ImageUploader

	

	validates_presence_of :name, :price, :stock_quantity
	validates_numericality_of :price, :stock_quantity

	belongs_to :designer
	belongs_to :category
	belongs_to :page

	def self.search(query)
		
     where("name LIKE ? OR description LIKE ?", "%#{query}%", "%#{query}%") 
    end


end

app/models/stockist.rb
class Stockist < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name, :address, :city, :country, :postal_code

  def full_address
  <<EOF
#{address}
#{postal_code} #{city}
#{country}
EOF
  end

	def admin?
  		self.admin
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :initialize_cart
  protect_from_forgery with: :exception
  before_action :find_categories
  before_action :find_designers


  def initialize_cart
  	@cart = Cart.build_from_hash session
  end

  def find_categories
  	@categories = Category.all
  end

  def find_designers
    @designers = Designer.all
  end

  def authenticate_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: "You are not allowed to perform that operation."
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_filter :initialize_cart

	def add
		@cart.add_item params[:id]
		session["cart"] = @cart.serialize
		product = Product.find params[:id]
		product.update_columns(stock_quantity: product.stock_quantity - 1)
		redirect_to :back, notice: "Added #{product.name} to cart."
	end

	def show

	end

	def checkout
		@order_form = OrderForm.new user: User.new
		@client_token = Braintree::ClientToken.generate
	end


    def remove
        cart = session['cart']
        item = cart['items'].find { |item| item['product_id'] == params[:id] }

        product = Product.find(item['product_id'])
        product.update_columns(stock_quantity: product.stock_quantity + 1)

        if item
            cart['items'].delete item
        end
      redirect_to cart_path
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :initialize_cart

  def index
    @orders = Order.order(created_at: :desc).all
  end

  def create
    @order_form = OrderForm.new(
      user: User.new(order_params[:user]),
      cart: @cart
    )

    if @order_form.save
      notify_user
      if false#charge_user
        redirect_to root_path, notice: "Thank you for placing the order."
      else
        flash[:warning] = <<EOF
We have stored your order with the id of #{@order_form.order.id}.
You should receive an email with the order details and password change.<br/>
However, something went wrong with your credit card, please add another one.
EOF
        redirect_to new_payment_order_path(@order_form.order)
      end
    else
      render "carts/checkout"
    end
  end

  def update
    @order = Order.find params[:id]
    @previous_state = @order.state

    if @order.update state_order_params
      notify_user_about_state
      redirect_to orders_path, notice: "Order was updated."
    end
  end

  def new_payment
    @order = Order.find params[:id]
    @client_token = Braintree::ClientToken.generate
  end

  def pay
    @order = Order.find params[:id]
    transaction = OrderTransaction.new @order, params[:payment_method_nonce]
    transaction.execute
    if transaction.ok?
      redirect_to root_path, notice: "Thank you for placing the order."
    else
      render "orders/new_payment"
    end
  end

  private

  def notify_user
    @order_form.user.send_reset_password_instructions
    OrderMailer.order_confirmation(@order_form.order).deliver
  end

  def notify_user_about_state
    OrderMailer.state_changed(@order, @previous_state).deliver
  end

  def order_params
    params.require(:order_form).permit(
      user: [ :name, :phone, :address, :city, :country, :postal_code, :email ]
    )
  end

  def charge_user
    transaction = OrderTransaction.new @order, params[:payment_method_nonce]
    transaction.execute
    transaction.ok?
  end

  def state_order_params
    params.require(:order).permit(:state)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	   @products = Product.all.order(created_at: :desc).group_by(&:category_id)
  	 
  end

  def about
  end

  def location
  end

  def stockists

  end

  def help
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/categories_helper.rb
module CategoriesHelper


end

app/helpers/category_names_helper.rb
module CategoryNamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/stockists_helper.rb
module StockistsHelper
end

app/views/application/_cart.html.erb
<% if @cart %>

 <li class="dropdown full-width navbar-right cart-wrapper">
     
             <% if @cart.empty? %>
                        Cart 0
                 <% else %>

                 <%= link_to "Cart #{pluralize @cart.count, "item"}", cart_path %>
             <% end %>
     
                    
 </li>

<% end %>

app/views/application/_footer.html.erb
   <footer id="footer" class="footer">
      <div class="row">
        <div class="container-fluid">

        <div class="col-xs-12 col-md-3 text-center">
        
        
         <a href="https://www.instagram.com/hlinreykdalstudio/"><i class="fa fa-instagram" aria-hidden="true"></i></a>

          <a href="https://www.facebook.com/Hl%C3%ADn-Reykdal-208910763506/?fref=ts"> <i class="fa fa-facebook-square" aria-hidden="true"></i></a>

         <i class="fa fa-envelope" aria-hidden="true"></i>

        </div>
       
         <div class="col-xs-12 col-md-3 text-center pull-right" id="footer_nav">
            <ul>  
                        <h5>Categories</h5>
                         <% @categories.each do |category| %>
                            <li><%= link_to category.name, category %></li>
                        <% end %>  
            </ul>
           
            </div>  
            <div class="col-xs-12 col-md-3 text-center pull-right" id="footer_nav">
                <ul>
                      <h5>Designers</h5>
                
                       <% @designers.each do |designer| %>
                            <li><%= link_to designer.designer_name, designer %></li>
                        <% end %>   
                              
                </ul>   
                    
            </div>          
            
                
              <div class="col-xs-12 col-md-3 text-center pull-right" id="footer_nav">

              <h5>Info</h5>
                    <ul>                   
                         <li><%= link_to "About", pages_about_path %></li>
                        
                        <li><%= link_to "Stockists", stockists_path %></li> 
                    
                        
                        <li><a href="#">Location</a></li>
                        
                        <li><%= link_to "Help", pages_help_path %></li> 
                        
                    </ul>
             </div>
        </div>
        </div>
      
    </footer>

app/views/application/_login.html.erb
      <div id="site-wrapper">

		<div id="site-canvas">

      		<div id="site-menu">
      			<span id='close' onclick='this.parentNode.parentNode.parentNode.removeChild(this.parentNode.parentNode); return false;'><button class="close-canvas"></button></span>
			<%= form_for(:user, :url => session_path(:user)) do |f| %>

			  <div class="form-group red">

			  	<%= f.label :email %>
  				<%= f.text_field :email, class: 'form-control' %><br>
  				<br>
  				<%= f.label :password %>
 				<%= f.password_field :password, class: 'form-control'  %><br>
 				<br>
  				<%= f.check_box :remember_me %>
  				<%= f.label :remember_me %><br>
 				<p><%= f.submit 'Sign in' %></p><br>
 				<br>
  				<%= link_to "Forgot your password?", new_password_path(:user) %>
  			  </div>	
			<% end %>
            </div>
      

    	</div><!-- #site-canvas -->
 	  </div><!-- #site-wrapper> -->


 	

app/views/application/_navbar.html.erb
  <div class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">		
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" 
                    data-toggle="collapse" 
                    data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <%= link_to image_tag("logo.svg", style:'height:auto;width:168px;'), root_path, class: 'navbar-brand' %>
          
        </div>
        <!-- Navbar Links -->
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown full-width">
                    <a href="#" class="dropdown-toggle" 
                    data-toggle="dropdown">
                        Shop
                    </a>


                    <ul class="dropdown-menu" role="menu">
                    

                        <% @categories.each do |category| %>
                            <li><%= link_to category.name, category %></li>
                        <% end %>    
                
                    </ul>
                </li>       
                   

                  <li class="dropdown full-width">
                    <a href="#" class="dropdown-toggle" 
                    data-toggle="dropdown">
                        Designers
                    </a>


                    <ul class="dropdown-menu" role="menu">
                    
                       
                       <% @designers.each do |designer| %>
                            <li><%= link_to designer.designer_name, designer %></li>
                        <% end %>    
                           
                       
                 
                        
                    </ul>
                </li>       


      
                <li class="dropdown full-width">
                    <a href="#" class="dropdown-toggle" 
                    data-toggle="dropdown">
                        Info
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "About", pages_about_path %></li>
                        
                        <li><%= link_to "Stockists", stockists_path %></li> 
                    
                        <li class="divider"></li>
                        <li><a href="#">Location</a></li>
                        <li class="divider"></li>
                        <li><%= link_to "Help", pages_help_path %></li> 
                    </ul>
                </li>          
            <% if current_user && current_user.admin? %>
             <li class="dropdown full-width">
                    <a href="#" class="dropdown-toggle" 
                    data-toggle="dropdown">
                        Admin
                    </a>
                    
                    <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "Products", products_path %></li>
                        <li><%= link_to "Categories", categories_path %></li>
                        <li><%= link_to "Designers", designers_path %></li>
                        <li><%= link_to "Stockists", stockists_path %></li>
                        <li><%= link_to "Orders", orders_path %></li>
                       
                    </ul>

                </li>   

                <% else %> 
               
            <% end %>

          

                <%= render 'cart'%>    
                <li class="dropdown full-width">
                    <a href="#" class="dropdown-toggle" 
                    data-toggle="dropdown">
                       <span class="glyphicon glyphicon-search"></span>
                    </a>
                     <ul class="dropdown-menu" role="menu">
                        <%= render 'search' %> 
                    </ul>
                  </li>
                        
                              <% if user_signed_in? %>
               
                <li class="dropdown full-width">
                   <!--<p class="navbar-link loggin-style"> Logged in as <%#= current_user.name %>.</p> -->
                   </li>
                   <li>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>    
                <% else %>
                <li class="dropdown full-width">
                    <a href="#" class="dropdown-toggle" 
                    data-toggle="dropdown">
                       Log in
                    </a>
                    <%#= link_to "Login", new_user_session_path, class: "toggle-nav" %>
                     <ul class="dropdown-menu" role="menu">
                    <%= form_for(:user, :url => session_path(:user)) do |f| %>

              <div class="form-group red">

                <%= f.label :email %>
                <%= f.text_field :email, class: 'form-control' %><br>
                <br>
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control'  %><br>
                <br>
                <%= f.check_box :remember_me %>
                <%= f.label :remember_me %><br>
                <p><%= f.submit 'Sign in' %></p><br>
                <br>
                <%= link_to "Forgot your password?", new_password_path(:user) %>
              </div>  
               </ul>  
            <% end %>
            </div>


                 <!--<a href="#" class="toggle-nav">Log in</a>-->

                <% end %>        
                    
                    
                </li>     
            </ul>
        </div>
       </div> 
    </div>

    <script src="js/bootstrap.min.js" type="text/javascript"></script>
<script>
  /**
 * Listen to scroll to change header opacity class
 */
function checkScroll(){
    var startY = $('.navbar').height() * 2; //The point where the navbar changes in px

    if($(window).scrollTop() > startY){
        $('.navbar').addClass("scrolled");
    }else{
        $('.navbar').removeClass("scrolled");
    }
}

if($('.navbar').length > 0){
    $(window).on("scroll load resize", function(){
        checkScroll();
    });
}
</script>
<script>
    $('.dropdown').hover(
        function() {
            $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn();
        }, 
        function() {
            $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut();
        }
    );

    $('.dropdown-menu').hover(
        function() {
            $(this).stop(true, true);
        },
        function() {
            $(this).stop(true, true).delay(200).fadeOut();
        }
    );
</script>

app/views/application/_notifications.html.erb
<div id="site-notification">
	<div>
		<p class="postlist-text"data-toggle="modal" data-target="#myModal">Please subscribe to our postlist</p> 
		<button class="close"></button>
	</div>

</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Please subscribe to our post list</h4>
      </div>
      <div class="modal-body">
        <%= render 'emaillist/email' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function(){
    $("#site-notification").click(function(){
        $("#site-notification").hide();
    });
        
});
</script>

app/views/application/_search.html.erb
<li class=" navbar-right searchbar">

<%= form_tag search_products_path, method: 'get', class: 'navbar-form' do %>
    <%= text_field_tag :query, params[:query], placeholder: "Enter search term", class: "form-control transparent-input",
        :style => "padding-left:29px" %>
    <%= button_tag(type: 'submit', class: "search-button transparent-input") do %> <span class="glyphicon glyphicon-search "></span>   
  
    <% end %>
<% end %>

</li>

app/views/application/_stockists.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stockist.name %>
</p>



<p>
  <strong>Address:</strong>
  <%= @stockist.address %>
</p>

<p>
  <strong>Website:</strong>
  <%= link_to @stockist.website %>
</p>



<%= link_to 'Edit', edit_stockist_path(@stockist) %> |
<%= link_to 'Back', stockists_path %>