config/routes.rb
Rails.application.routes.draw do
  resources :stockists
  post 'emaillist/subscribe' => 'emaillist#subscribe'

  get 'products/search' => 'products#search', as: 'search_products'

  get 'pages/index'

  get 'pages/about'

  get 'pages/location'

  get 'pages/help'

  devise_for :users
  resources :categories
  resources :categories
  resources :designers
  resources :category_names

  resources :products

  resource :cart, only: [:show] do
    post "add", path: "add/:id", on: :member
    delete 'remove', path: 'destroy/:id'
    get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update ] do
    member do
      get :new_payment
      post :pay
    end
  end
  

  

  root 'pages#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	

	mount_uploader :image, ImageUploader

	

	validates_presence_of :name, :price, :stock_quantity
	validates_numericality_of :price, :stock_quantity

	belongs_to :designer
	belongs_to :category
	belongs_to :page

	def self.search(query)
		
     where("name LIKE ? OR description LIKE ?", "%#{query}%", "%#{query}%") 
    end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :initialize_cart
  before_action :authenticate_admin!, only: [ :new, :edit, :update, :create, :destroy ]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  def search
    
    @products = Product.search(params[:query]).order("created_at DESC")
    @categories = Category.joins(:products).where(:products => {:id => @products.map{|x| x.id }}).distinct

  end

  # GET /products/1
  # GET /products/1.json
  def show

  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit

  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image, :category_id, :stock_quantity, :designer_id, :query)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, multipart: true do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
      <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "form-control", rows: "5" %>
      </div>
      <div class="form-group">
          <%= f.label :designer %><br>
          <%= f.select :designer_id, Designer.all.map { |c| [ c.designer_name, c.id ] } %>

      </div>
      <div class="form-group">
          <%= f.label :description %><br>
          <%= f.text_area :description, class: "form-control", rows: "5"  %>
      </div>
      <div class="form-group">
         <%= f.label :price %><br>
         <%= f.text_field :price %>
      </div>
      <div class="form-group">
         <%= f.label :image %><br>
         <%= f.file_field :image %>
      </div>

     <div class="form-group">
         <%= f.label :stock_quantity %><br>
          <%= f.number_field :stock_quantity %>
      </div>

      <div class="form-group">
          <%= f.label :category %><br>
          <%= f.select :category_id, Category.all.map { |c| [ c.name, c.id ] } %>
       </div>
        <div class="actions">
          <%= f.submit %>
        </div>
  <% end %>
</div>

app/views/products/_table.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Designer</th>
      <th>Price</th>
      <th>Stock</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product %></td>
        <td><%= product.description %></td>
        <td><%= product.designer.designer_name %></td>

        <td><%= number_to_currency product.price %></td>
        <td><%= product.stock_quantity %></td>

        <td><%= image_tag product.image.thumb %></td>
     <% if current_user && current_user.admin? %>   
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>
<%= render "products/table", products: @products %>

<% if current_user && current_user.admin? %>
		<p><%= link_to 'New Product', new_product_path, class: "btn btn-primary" %></p>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<div class="container">
<div class="row product_top">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Designer</th>
      <th>Price</th>
      <th>Stock</th>
      <th>Image</th>
      
    </tr>
  </thead>

<tbody>
  <% @products.each do |product| %>
    
      <tr>
        <td><%= link_to product.name, product %></td>
        <td><%= product.description %></td>
        <td><%= product.designer.designer_name %></td>

        <td><%= number_to_currency product.price %></td>
        <td><%= product.stock_quantity %></td>

        <td><%= image_tag product.image.thumb %></td>
      
 
  <% end %>
  </tr>
</tbody>
</table>
</div>
</div>

app/views/products/show.html.erb
<div class="row product_top">
    
    <div class="container-fluid">
	 
    <% breadcrumb :products %>

    <div class="col-xs-12 col-sm-6 center-block">
    
       
     <div class="product_description">

        <h3><%= @product.name %></h3>
        <h4><%#=@product.material %></h4>
        <p><%= @product.description %></p>
        <p><%= @product.designer.designer_name %></p>

        <p>In stock: <%= @product.stock_quantity %> </p>
     </div>
      	<div class="col-xs-12">
       	 <p class="price"> <%= number_to_currency @product.price %></p>
    	</div>
    	<div class="row add_to_cart">	
        	<p><%= link_to 'Add to cart', add_cart_path, method: :post %></p>
        </div>
  
   
    </div>

      
   <div class="col-xs-12 col-sm-6 center-block" >
    
  <%= image_tag @product.image.url(:medium), class: "img-responsive"  %>

  

  </div>



  </div>  
  <p>
  <% if current_user && current_user.admin? %>
	 <%= link_to 'Edit', edit_product_path(@product) %> |
  <% end %>
	 <%= link_to 'Back',  root_path %>
</p>
</div>